/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaselineRouteImport } from './routes/baseline'
import { Route as CandidateRouteImport } from './routes/candidate'
import { Route as DataRouteImport } from './routes/data'
import { Route as EaRouteImport } from './routes/ea'
import { Route as FiltersRouteImport } from './routes/filters'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProtocolRouteImport } from './routes/protocol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaselineRoute = BaselineRouteImport.update({
  id: '/baseline',
  path: '/baseline',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRoute = CandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const EaRoute = EaRouteImport.update({
  id: '/ea',
  path: '/ea',
  getParentRoute: () => rootRouteImport,
} as any)
const FiltersRoute = FiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baseline': typeof BaselineRoute
  '/candidate': typeof CandidateRoute
  '/data': typeof DataRoute
  '/ea': typeof EaRoute
  '/filters': typeof FiltersRoute
  '/plan': typeof PlanRoute
  '/protocol': typeof ProtocolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baseline': typeof BaselineRoute
  '/candidate': typeof CandidateRoute
  '/data': typeof DataRoute
  '/ea': typeof EaRoute
  '/filters': typeof FiltersRoute
  '/plan': typeof PlanRoute
  '/protocol': typeof ProtocolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baseline': typeof BaselineRoute
  '/candidate': typeof CandidateRoute
  '/data': typeof DataRoute
  '/ea': typeof EaRoute
  '/filters': typeof FiltersRoute
  '/plan': typeof PlanRoute
  '/protocol': typeof ProtocolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baseline'
    | '/candidate'
    | '/data'
    | '/ea'
    | '/filters'
    | '/plan'
    | '/protocol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/baseline'
    | '/candidate'
    | '/data'
    | '/ea'
    | '/filters'
    | '/plan'
    | '/protocol'
  id:
    | '__root__'
    | '/'
    | '/baseline'
    | '/candidate'
    | '/data'
    | '/ea'
    | '/filters'
    | '/plan'
    | '/protocol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaselineRoute: typeof BaselineRoute
  CandidateRoute: typeof CandidateRoute
  DataRoute: typeof DataRoute
  EaRoute: typeof EaRoute
  FiltersRoute: typeof FiltersRoute
  PlanRoute: typeof PlanRoute
  ProtocolRoute: typeof ProtocolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseline': {
      id: '/baseline'
      path: '/baseline'
      fullPath: '/baseline'
      preLoaderRoute: typeof BaselineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate': {
      id: '/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ea': {
      id: '/ea'
      path: '/ea'
      fullPath: '/ea'
      preLoaderRoute: typeof EaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filters': {
      id: '/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof FiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaselineRoute: BaselineRoute,
  CandidateRoute: CandidateRoute,
  DataRoute: DataRoute,
  EaRoute: EaRoute,
  FiltersRoute: FiltersRoute,
  PlanRoute: PlanRoute,
  ProtocolRoute: ProtocolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
